development: &default
  adapter: postgresql
  database: bokken_dev
  encoding: utf8
  host: localhost
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

test:
  <<: *default
  database: bokken_test

production:
  <<: *default
  database: bokken
